# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c63efbc1fb350a25114fbcccc5d29dac8527cfd5d49e6d021367b994ecc570c4b58b397bccbbef88b0b86564c075b751c2dbe6b9f36aff3296c3f4c088ff2ba

test:
  secret_key_base: 9847b6e2d6aaae586ef50762007fbad7b41a8b589883c8afdd0f5a839667f0e4c3d85259ae84dc9265ba850e58a84e52a918714d39fb55f558b2f2f1b4bcc372

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
